// 六足战车模型配置
// 通过 window.HexapodConfig 全局暴露
(function () {
  'use strict';

  const HEXAPOD_CONFIG = {
    name: '六足战车',
    type: 'Group',
    position: [0, 0, 0],
    children: [
      {
        name: '车体',
        type: 'Group',
        children: [
          {
            name: '下车体',
            type: 'TaperedBox',
            size: [1.075, 0.5, 1, 1.6, 1.5, 0, 0],
            position: [0, 0.25, 0],
            materialId: 'armor_dark',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '上车体',
            type: 'TaperedBox',
            size: [1, 0.6, 0.9, 1.4, 1.2, 0, 0],
            position: [0, 0.805, 0],
            materialId: 'armor_dark',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '前装甲',
            type: 'Box',
            size: [0.1, 0.4, 1],
            position: [-0.6, 0.71, 0],
            materialId: 'armor_dark',
            rotation: [0, 0, 0.35],
            visible: true,
          },
          {
            name: '后装甲板',
            type: 'Box',
            size: [0.12, 0.5, 1.2],
            position: [0.6, 0.755, 0],
            materialId: 'armor_dark',
            rotation: [0, 0, 2.7053],
            visible: true,
          },
          {
            name: '左侧裙板',
            type: 'Box',
            size: [1.6, 0.15, 0.06],
            position: [0, 0.52, -0.75],
            materialId: 'armor_dark',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '右侧裙板',
            type: 'Box',
            size: [1.6, 0.15, 0.06],
            position: [0, 0.52, 0.75],
            materialId: 'armor_dark',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '观瞄球体',
            type: 'Sphere',
            size: [0.3],
            segments: [12, 8],
            position: [0, 1.4, 0],
            materialId: 'steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '观瞄底座',
            type: 'Cylinder',
            size: [0.25, 0.08, 0.25],
            segments: [16],
            position: [0, 1.125, 0],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '观察缝',
            type: 'Box',
            size: [0.06, 0.04, 0.4],
            position: [-0.65, 0.65, 0],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '顶部面板',
            type: 'Box',
            size: [1.4, 0.04, 1.2],
            position: [0, 1.125, 0],
            materialId: 'armor_light',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '左散热口',
            type: 'Box',
            size: [0.3, 0.02, 0.4],
            position: [0.5, 1.15, -0.25],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '右散热口',
            type: 'Box',
            size: [0.3, 0.02, 0.4],
            position: [0.5, 1.15, 0.25],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '左前警示条',
            type: 'Box',
            size: [0.005, 0.04, 0.25],
            position: [-0.4, 0.54, -0.78],
            materialId: 'warning_yellow',
            rotation: [0, 1.5534, 0],
            visible: true,
          },
          {
            name: '右前警示条',
            type: 'Box',
            size: [0.005, 0.04, 0.25],
            position: [-0.4, 0.54, 0.78],
            materialId: 'warning_yellow',
            rotation: [0, -1.5708, 0],
            visible: true,
          },
          {
            name: '左后警示条',
            type: 'Box',
            size: [0.005, 0.04, 0.25],
            position: [0.4, 0.54, -0.78],
            materialId: 'warning_yellow',
            rotation: [0, 1.5534, 0],
            visible: true,
          },
          {
            name: '右后警示条',
            type: 'Box',
            size: [0.005, 0.04, 0.25],
            position: [0.4, 0.54, 0.78],
            materialId: 'warning_yellow',
            rotation: [0, -1.5708, 0],
            visible: true,
          },
        ],
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        visible: true,
      },
      {
        name: '左武器平台',
        type: 'Group',
        position: [-0.2, 0.75, -1.1],
        children: [
          {
            name: '左加特林',
            type: 'Group',
            pivot: [0, 0, 0],
            children: [
              {
                name: '左加特林护套',
                type: 'Cylinder',
                size: [0.1, 0.45, 0.1],
                segments: [16],
                position: [-0.25, 0, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左加特林枪管1',
                type: 'Cylinder',
                size: [0.025, 0.6, 0.025],
                segments: [8],
                position: [-0.5, 0.04, 0],
                materialId: 'barrel_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左加特林枪管2',
                type: 'Cylinder',
                size: [0.025, 0.6, 0.025],
                segments: [8],
                position: [-0.5, -0.04, 0],
                materialId: 'barrel_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左加特林枪管3',
                type: 'Cylinder',
                size: [0.025, 0.6, 0.025],
                segments: [8],
                position: [-0.5, 0, 0.04],
                materialId: 'barrel_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左加特林枪管4',
                type: 'Cylinder',
                size: [0.025, 0.6, 0.025],
                segments: [8],
                position: [-0.5, 0, -0.04],
                materialId: 'barrel_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左加特林弹链',
                type: 'Box',
                size: [0.12, 0.15, 0.2],
                position: [0.05, -0.1, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '左加特林支架',
                type: 'Sphere',
                size: [0.03],
                position: [-0.1, 0, 0.125],
                materialId: 'default',
                rotation: [0, 0, 0],
                visible: true,
                segments: [8, 6],
              },
            ],
            position: [0, 0, 0.45],
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '左导弹巢',
            type: 'Group',
            position: [0.75, 0.3, 0.4],
            pivot: [0, 0, 0],
            children: [
              {
                name: '左导弹外壳',
                type: 'Box',
                size: [0.14, 0.2, 0.16],
                materialId: 'armor_dark',
                position: [0, 0, 0],
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '左导弹管1',
                type: 'Cylinder',
                size: [0.05, 0.4, 0.05],
                segments: [8],
                position: [-0.22, 0.03, 0.03],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左导弹管2',
                type: 'Cylinder',
                size: [0.05, 0.4, 0.05],
                segments: [8],
                position: [-0.22, -0.03, 0.03],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左导弹管3',
                type: 'Cylinder',
                size: [0.05, 0.4, 0.05],
                segments: [8],
                position: [-0.22, 0.03, -0.03],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左导弹管4',
                type: 'Cylinder',
                size: [0.05, 0.4, 0.05],
                segments: [8],
                position: [-0.22, -0.03, -0.03],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '左导弹支架',
                type: 'Sphere',
                size: [0.03],
                position: [0, 0, 0.1],
                materialId: 'default',
                rotation: [0, 0, 0],
                visible: true,
                segments: [8, 6],
              },
            ],
            rotation: [0, 0, -0.5236],
            visible: true,
          },
        ],
        rotation: [0, 0, 0],
        visible: true,
      },
      {
        name: '右武器平台',
        type: 'Group',
        position: [-0.2, 0.75, 1.1],
        children: [
          {
            name: '右加特林',
            type: 'Group',
            pivot: [0, 0, 0],
            children: [
              {
                name: '右加特林护套',
                type: 'Cylinder',
                size: [0.1, 0.45, 0.1],
                segments: [16],
                position: [-0.25, 0, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右加特林枪管1',
                type: 'Cylinder',
                size: [0.025, 0.6, 0.025],
                segments: [8],
                position: [-0.5, 0.04, 0],
                materialId: 'barrel_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右加特林枪管2',
                type: 'Cylinder',
                size: [0.025, 0.6, 0.025],
                segments: [8],
                position: [-0.5, -0.04, 0],
                materialId: 'barrel_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右加特林枪管3',
                type: 'Cylinder',
                size: [0.025, 0.6, 0.025],
                segments: [8],
                position: [-0.5, 0, 0.04],
                materialId: 'barrel_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右加特林枪管4',
                type: 'Cylinder',
                size: [0.025, 0.6, 0.025],
                segments: [8],
                position: [-0.5, 0, -0.04],
                materialId: 'barrel_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右加特林弹链',
                type: 'Box',
                size: [0.12, 0.15, 0.2],
                position: [0.05, -0.1, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '右加特林支架',
                type: 'Sphere',
                size: [0.03],
                position: [-0.1, 0, -0.125],
                materialId: 'default',
                rotation: [0, 0, 0],
                visible: true,
                segments: [8, 6],
              },
            ],
            position: [0, 0, -0.45],
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '右导弹巢',
            type: 'Group',
            position: [0.75, 0.3, -0.4],
            pivot: [0, 0, 0],
            children: [
              {
                name: '右导弹外壳',
                type: 'Box',
                size: [0.14, 0.2, 0.16],
                materialId: 'armor_dark',
                position: [0, 0, 0],
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '右导弹管1',
                type: 'Cylinder',
                size: [0.05, 0.4, 0.05],
                segments: [8],
                position: [-0.22, 0.03, 0.03],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右导弹管2',
                type: 'Cylinder',
                size: [0.05, 0.4, 0.05],
                segments: [8],
                position: [-0.22, -0.03, 0.03],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右导弹管3',
                type: 'Cylinder',
                size: [0.05, 0.4, 0.05],
                segments: [8],
                position: [-0.22, 0.03, -0.03],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右导弹管4',
                type: 'Cylinder',
                size: [0.05, 0.4, 0.05],
                segments: [8],
                position: [-0.22, -0.03, -0.03],
                materialId: 'dark_steel',
                rotation: [0, 0, 1.5708],
                visible: true,
              },
              {
                name: '右导弹支架',
                type: 'Sphere',
                size: [0.03],
                position: [0, 0, -0.1],
                materialId: 'default',
                rotation: [0, 0, 0],
                visible: true,
                segments: [8, 6],
              },
            ],
            rotation: [0, 0, -0.5236],
            visible: true,
          },
        ],
        rotation: [0, 0, 0],
        visible: true,
      },
      {
        name: '左前腿',
        type: 'Group',
        position: [-0.5, 0.05, 0.55],
        children: [
          {
            name: '左前大腿',
            type: 'TaperedBox',
            size: [0.14, 0.7, 0.14, 0.1, 0.1],
            position: [0, -0.35, 0],
            pivot: [0, 0.35, 0],
            materialId: 'armor_dark',
            children: [
              {
                name: '左前小腿',
                type: 'TaperedBox',
                size: [0.1, 0.55, 0.1, 0.07, 0.07],
                position: [0, -0.625, 0],
                pivot: [0, 0.275, 0],
                materialId: 'armor_dark',
                children: [
                  {
                    name: '左前膝球',
                    type: 'Sphere',
                    size: [0.05],
                    segments: [6, 4],
                    position: [0, 0.275, 0],
                    materialId: 'dark_steel',
                    rotation: [0, 0, 0],
                    visible: true,
                  },
                  {
                    name: '左前脚踝',
                    type: 'Group',
                    position: [0, -0.3, 0],
                    pivot: [0, 0, 0],
                    rotation: [0, 0, 0],
                    visible: true,
                    children: [
                      {
                        name: '左前踝球',
                        type: 'Sphere',
                        size: [0.05],
                        segments: [8, 6],
                        position: [0, 0, 0],
                        materialId: 'dark_steel',
                        rotation: [0, 0, 0],
                        visible: true,
                      },
                      {
                        name: '左前尖刺足',
                        type: 'Cylinder',
                        size: [0.055, 0.28, 0.001],
                        segments: [8],
                        position: [0, -0.17, 0],
                        materialId: 'dark_steel',
                        rotation: [0.2, 0, 0],
                        visible: true,
                        pivot: [0, 0.14, 0],
                      },
                    ],
                  },
                ],
                rotation: [1.4, 0, 0],
                visible: true,
              },
              {
                name: '左前髋球',
                type: 'Sphere',
                size: [0.06],
                segments: [6, 4],
                position: [0, 0.35, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '左前腿警示条',
                type: 'Box',
                size: [0.15, 0.03, 0.005],
                position: [0, -0.15, 0.075],
                materialId: 'warning_yellow',
                rotation: [0, 0, 0],
                visible: true,
              },
            ],
            rotation: [-2.09, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, -1.05, 0],
        visible: true,
      },
      {
        name: '右前腿',
        type: 'Group',
        position: [-0.5, 0.05, -0.55],
        children: [
          {
            name: '右前大腿',
            type: 'TaperedBox',
            size: [0.14, 0.7, 0.14, 0.1, 0.1],
            position: [0, -0.35, 0],
            pivot: [0, 0.35, 0],
            materialId: 'armor_dark',
            children: [
              {
                name: '右前小腿',
                type: 'TaperedBox',
                size: [0.1, 0.55, 0.1, 0.07, 0.07],
                position: [0, -0.625, 0],
                pivot: [0, 0.275, 0],
                materialId: 'armor_dark',
                children: [
                  {
                    name: '右前膝球',
                    type: 'Sphere',
                    size: [0.05],
                    segments: [6, 4],
                    position: [0, 0.275, 0],
                    materialId: 'dark_steel',
                    rotation: [0, 0, 0],
                    visible: true,
                  },
                  {
                    name: '右前脚踝',
                    type: 'Group',
                    position: [0, -0.3, 0],
                    pivot: [0, 0, 0],
                    rotation: [0, 0, 0],
                    visible: true,
                    children: [
                      {
                        name: '右前踝球',
                        type: 'Sphere',
                        size: [0.05],
                        segments: [8, 6],
                        position: [0, 0, 0],
                        materialId: 'dark_steel',
                        rotation: [0, 0, 0],
                        visible: true,
                      },
                      {
                        name: '右前尖刺足',
                        type: 'Cylinder',
                        size: [0.055, 0.28, 0.001],
                        segments: [8],
                        position: [0, -0.17, 0],
                        materialId: 'dark_steel',
                        rotation: [-0.2, 0, 0],
                        visible: true,
                        pivot: [0, 0.14, 0],
                      },
                    ],
                  },
                ],
                rotation: [-1.4, 0, 0],
                visible: true,
              },
              {
                name: '右前髋球',
                type: 'Sphere',
                size: [0.06],
                segments: [6, 4],
                position: [0, 0.35, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '右前腿警示条',
                type: 'Box',
                size: [0.15, 0.03, 0.005],
                position: [0, -0.15, -0.075],
                materialId: 'warning_yellow',
                rotation: [0, 0, 0],
                visible: true,
              },
            ],
            rotation: [2.09, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, 1.05, 0],
        visible: true,
      },
      {
        name: '左中腿',
        type: 'Group',
        position: [0, 0.05, 0.55],
        children: [
          {
            name: '左中大腿',
            type: 'TaperedBox',
            size: [0.14, 0.7, 0.14, 0.1, 0.1],
            position: [0, -0.35, 0],
            pivot: [0, 0.35, 0],
            materialId: 'armor_dark',
            children: [
              {
                name: '左中小腿',
                type: 'TaperedBox',
                size: [0.1, 0.55, 0.1, 0.07, 0.07],
                position: [0, -0.625, 0],
                pivot: [0, 0.275, 0],
                materialId: 'armor_dark',
                children: [
                  {
                    name: '左中膝球',
                    type: 'Sphere',
                    size: [0.05],
                    segments: [6, 4],
                    position: [0, 0.275, 0],
                    materialId: 'dark_steel',
                    rotation: [0, 0, 0],
                    visible: true,
                  },
                  {
                    name: '左中脚踝',
                    type: 'Group',
                    position: [0, -0.3, 0],
                    pivot: [0, 0, 0],
                    rotation: [0, 0, 0],
                    visible: true,
                    children: [
                      {
                        name: '左中踝球',
                        type: 'Sphere',
                        size: [0.05],
                        segments: [8, 6],
                        position: [0, 0, 0],
                        materialId: 'dark_steel',
                        rotation: [0, 0, 0],
                        visible: true,
                      },
                      {
                        name: '左中尖刺足',
                        type: 'Cylinder',
                        size: [0.055, 0.28, 0.001],
                        segments: [8],
                        position: [0, -0.17, 0],
                        materialId: 'dark_steel',
                        rotation: [0.2, 0, 0],
                        visible: true,
                        pivot: [0, 0.14, 0],
                      },
                    ],
                  },
                ],
                rotation: [1.4, 0, 0],
                visible: true,
              },
              {
                name: '左中髋球',
                type: 'Sphere',
                size: [0.06],
                segments: [6, 4],
                position: [0, 0.35, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '左中腿警示条',
                type: 'Box',
                size: [0.15, 0.03, 0.005],
                position: [0, -0.15, 0.075],
                materialId: 'warning_yellow',
                rotation: [0, 0, 0],
                visible: true,
              },
            ],
            rotation: [-2.09, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, 0, 0],
        visible: true,
      },
      {
        name: '右中腿',
        type: 'Group',
        position: [0, 0.05, -0.55],
        children: [
          {
            name: '右中大腿',
            type: 'TaperedBox',
            size: [0.14, 0.7, 0.14, 0.1, 0.1],
            position: [0, -0.35, 0],
            pivot: [0, 0.35, 0],
            materialId: 'armor_dark',
            children: [
              {
                name: '右中小腿',
                type: 'TaperedBox',
                size: [0.1, 0.55, 0.1, 0.07, 0.07],
                position: [0, -0.625, 0],
                pivot: [0, 0.275, 0],
                materialId: 'armor_dark',
                children: [
                  {
                    name: '右中膝球',
                    type: 'Sphere',
                    size: [0.05],
                    segments: [6, 4],
                    position: [0, 0.275, 0],
                    materialId: 'dark_steel',
                    rotation: [0, 0, 0],
                    visible: true,
                  },
                  {
                    name: '右中脚踝',
                    type: 'Group',
                    position: [0, -0.3, 0],
                    pivot: [0, 0, 0],
                    rotation: [0, 0, 0],
                    visible: true,
                    children: [
                      {
                        name: '右中踝球',
                        type: 'Sphere',
                        size: [0.05],
                        segments: [8, 6],
                        position: [0, 0, 0],
                        materialId: 'dark_steel',
                        rotation: [0, 0, 0],
                        visible: true,
                      },
                      {
                        name: '右中尖刺足',
                        type: 'Cylinder',
                        size: [0.055, 0.28, 0.001],
                        segments: [8],
                        position: [0, -0.17, 0],
                        materialId: 'dark_steel',
                        rotation: [-0.2, 0, 0],
                        visible: true,
                        pivot: [0, 0.14, 0],
                      },
                    ],
                  },
                ],
                rotation: [-1.4, 0, 0],
                visible: true,
              },
              {
                name: '右中髋球',
                type: 'Sphere',
                size: [0.06],
                segments: [6, 4],
                position: [0, 0.35, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '右中腿警示条',
                type: 'Box',
                size: [0.15, 0.03, 0.005],
                position: [0, -0.15, -0.075],
                materialId: 'warning_yellow',
                rotation: [0, 0, 0],
                visible: true,
              },
            ],
            rotation: [2.09, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, 0, 0],
        visible: true,
      },
      {
        name: '左后腿',
        type: 'Group',
        position: [0.5, 0.05, 0.55],
        children: [
          {
            name: '左后大腿',
            type: 'TaperedBox',
            size: [0.14, 0.7, 0.14, 0.1, 0.1],
            position: [0, -0.35, 0],
            pivot: [0, 0.35, 0],
            materialId: 'armor_dark',
            children: [
              {
                name: '左后小腿',
                type: 'TaperedBox',
                size: [0.1, 0.55, 0.1, 0.07, 0.07],
                position: [0, -0.625, 0],
                pivot: [0, 0.275, 0],
                materialId: 'armor_dark',
                children: [
                  {
                    name: '左后膝球',
                    type: 'Sphere',
                    size: [0.05],
                    segments: [6, 4],
                    position: [0, 0.275, 0],
                    materialId: 'dark_steel',
                    rotation: [0, 0, 0],
                    visible: true,
                  },
                  {
                    name: '左后脚踝',
                    type: 'Group',
                    position: [0, -0.3, 0],
                    pivot: [0, 0, 0],
                    rotation: [0, 0, 0],
                    visible: true,
                    children: [
                      {
                        name: '左后踝球',
                        type: 'Sphere',
                        size: [0.05],
                        segments: [8, 6],
                        position: [0, 0, 0],
                        materialId: 'dark_steel',
                        rotation: [0, 0, 0],
                        visible: true,
                      },
                      {
                        name: '左后尖刺足',
                        type: 'Cylinder',
                        size: [0.055, 0.28, 0.001],
                        segments: [8],
                        position: [0, -0.17, 0],
                        materialId: 'dark_steel',
                        rotation: [0.2, 0, 0],
                        visible: true,
                        pivot: [0, 0.14, 0],
                      },
                    ],
                  },
                ],
                rotation: [1.4, 0, 0],
                visible: true,
              },
              {
                name: '左后髋球',
                type: 'Sphere',
                size: [0.06],
                segments: [6, 4],
                position: [0, 0.35, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '左后腿警示条',
                type: 'Box',
                size: [0.15, 0.03, 0.005],
                position: [0, -0.15, 0.075],
                materialId: 'warning_yellow',
                rotation: [0, 0, 0],
                visible: true,
              },
            ],
            rotation: [-2.09, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, 1.05, 0],
        visible: true,
      },
      {
        name: '右后腿',
        type: 'Group',
        position: [0.5, 0.05, -0.55],
        children: [
          {
            name: '右后大腿',
            type: 'TaperedBox',
            size: [0.14, 0.7, 0.14, 0.1, 0.1],
            position: [0, -0.35, 0],
            pivot: [0, 0.35, 0],
            materialId: 'armor_dark',
            children: [
              {
                name: '右后小腿',
                type: 'TaperedBox',
                size: [0.1, 0.55, 0.1, 0.07, 0.07],
                position: [0, -0.625, 0],
                pivot: [0, 0.275, 0],
                materialId: 'armor_dark',
                children: [
                  {
                    name: '右后膝球',
                    type: 'Sphere',
                    size: [0.05],
                    segments: [6, 4],
                    position: [0, 0.275, 0],
                    materialId: 'dark_steel',
                    rotation: [0, 0, 0],
                    visible: true,
                  },
                  {
                    name: '右后脚踝',
                    type: 'Group',
                    position: [0, -0.3, 0],
                    pivot: [0, 0, 0],
                    rotation: [0, 0, 0],
                    visible: true,
                    children: [
                      {
                        name: '右后踝球',
                        type: 'Sphere',
                        size: [0.05],
                        segments: [8, 6],
                        position: [0, 0, 0],
                        materialId: 'dark_steel',
                        rotation: [0, 0, 0],
                        visible: true,
                      },
                      {
                        name: '右后尖刺足',
                        type: 'Cylinder',
                        size: [0.055, 0.28, 0.001],
                        segments: [8],
                        position: [0, -0.17, 0],
                        materialId: 'dark_steel',
                        rotation: [-0.2, 0, 0],
                        visible: true,
                        pivot: [0, 0.14, 0],
                      },
                    ],
                  },
                ],
                rotation: [-1.4, 0, 0],
                visible: true,
              },
              {
                name: '右后髋球',
                type: 'Sphere',
                size: [0.06],
                segments: [6, 4],
                position: [0, 0.35, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '右后腿警示条',
                type: 'Box',
                size: [0.15, 0.03, 0.005],
                position: [0, -0.15, -0.075],
                materialId: 'warning_yellow',
                rotation: [0, 0, 0],
                visible: true,
              },
            ],
            rotation: [2.09, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, -1.05, 0],
        visible: true,
      },
    ],
    rotation: [0, 1.5708, 0],
    visible: true,
  };

  // ── 共享动画参数表 (v0.58.0) ──
  // 模型工厂和游戏都从这里读取，修改即生效
  var ANIM_TABLE = [
    // idx  name              direction  turnRate  stride  stepH
    // 0=原地, ±1=X轴(前/后), ±2=Z轴(左/右平移); rad/s, 0=直行, >1=静态转
    [0, 'Idle', 0, 0, 0, 0],
    [1, 'Walk', 1, 0, 0.22, 0.15],
    [2, 'Run', 1, 0, 0.38, 0.24],
    [3, 'Walk Back', -1, 0, 0.18, 0.12],
    [4, 'Run Back', -1, 0, 0.28, 0.18],
    [5, 'Strafe Left', 2, 0, 0.14, 0.1],
    [6, 'Strafe Right', -2, 0, 0.14, 0.1],
    [7, 'Static Turn L', 1, 1.2, 0.135, 0.1],
    [8, 'Static Turn R', 1, -1.2, 0.135, 0.1],
    [9, 'Walk Turn L', 1, 0.5, 0.22, 0.15],
    [10, 'Walk Turn R', 1, -0.5, 0.22, 0.15],
    [11, 'Strafe Turn L', 2, -0.45, 0.14, 0.1],
    [12, 'Strafe Turn R', -2, 0.45, 0.14, 0.1],
    [13, 'Walk Back Turn L', -1, 0.5, 0.18, 0.12],
    [14, 'Walk Back Turn R', -1, -0.5, 0.18, 0.12],
    [15, 'Run Turn L', 1, 0.7, 0.38, 0.24],
    [16, 'Run Turn R', 1, -0.7, 0.38, 0.24],
    [17, 'Run Back Turn L', -1, 0.7, 0.28, 0.18],
    [18, 'Run Back Turn R', -1, -0.7, 0.28, 0.18],
    [19, 'Strafe Run L', 2, 0, 0.19, 0.18],
    [20, 'Strafe Run R', -2, 0, 0.19, 0.18],
    [21, 'Stagger', 0, 0, 0, 0],
    [22, 'Death', 0, 0, 0, 0],
  ];

  // 辅助函数：从ANIM_TABLE取字段
  function animField(idx, fieldIdx) {
    var row = idx >= 0 && idx < ANIM_TABLE.length ? ANIM_TABLE[idx] : ANIM_TABLE[0];
    return row[fieldIdx];
  }

  // 腿配置（当前六足专属）
  var LEG_CONFIG = {
    prefixes: ['左前', '右前', '左中', '右中', '左后', '右后'],
    tripodA: { 左前: true, 右中: true, 左后: true },
    yLimitFront: 0.45, // 前后腿 ±25°
    yLimitMiddle: 0.7, // 中腿 ±40°
  };

  // 死亡瘫倒预设（每腿的伸展倍率+角度偏移）
  var DEATH_SPLAY_PRESETS = [
    { mul: 1.18, ao: 0.55 }, // 左前
    { mul: 1.25, ao: -0.15 }, // 右前
    { mul: 1.22, ao: 0.08 }, // 左中
    { mul: 1.3, ao: -0.45 }, // 右中
    { mul: 1.15, ao: -0.5 }, // 左后
    { mul: 1.2, ao: 0.6 }, // 右后
  ];

  window.HexapodConfig = {
    HEXAPOD_CONFIG: HEXAPOD_CONFIG,
    ANIM_TABLE: ANIM_TABLE,
    animField: animField,
    LEG_CONFIG: LEG_CONFIG,
    DEATH_SPLAY_PRESETS: DEATH_SPLAY_PRESETS,
    // 碰撞体 — 优先模型减面，兜底 Box
    COLLISION_PARTS: [
      {
        parent: 'group',
        tag: 'body',
        color: 0xff8844,
        nameExclude: ['加特林', '导弹', '观瞄'],
        maxY: 1.5,
      },
    ],
    COLLISION_SHAPES: [
      { parent: 'group', type: 'box', pos: [0, 0.9, 0], size: [2.0, 1.3, 2.4], tag: 'body' },
    ],
  };
})();
