// 模型配置数据 — 与 model_factory.html 分离
// 通过 window.ModelConfigs 全局暴露
(function () {
  'use strict';

  // ============================================================
  const T34_85_V16_CONFIG = {
    name: 'T-34/85 v1.6',
    type: 'Group',
    position: [0, -0.15, 0],
    rotation: [0, 0, 0],
    scale: [0.5, 0.5, 0.5],
    children: [
      {
        name: '车体',
        type: 'Group',
        position: [0, 0, 0],
        children: [
          {
            name: '下车体',
            type: 'TaperedBox',
            size: [2, 0.4, 4.04, 2, 6, 0, -0.05],
            position: [0, 0.85, -0.1],
            materialId: 'camo_green',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '上车体',
            type: 'TaperedBox',
            size: [2.6, 0.7, 6, 1.935, 3.465, 0, -0.45],
            position: [0, 1.4, -0.1],
            materialId: 'camo_green',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '发动机舱',
            type: 'Box',
            size: [1.8, 0.12, 0.6],
            position: [0, 1.8, -1.3],
            materialId: 'camo_dark',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '左前翼子板',
            type: 'BentBox',
            size: [0.6, 0.06, 0.96, 1.06],
            position: [-1.2, 1.08, 2.7],
            materialId: 'camo_green',
            rotation: [0.4887, 0, 3.1416],
            visible: true,
            segments: [32],
          },
          {
            name: '右前翼子板',
            type: 'BentBox',
            size: [0.6, 0.06, 0.96, 1.06],
            position: [1.2, 1.08, 2.7],
            materialId: 'camo_green',
            rotation: [0.4887, 0, 3.1416],
            visible: true,
            segments: [32],
          },
          {
            name: '左侧翼子板',
            type: 'Box',
            size: [0.3, 0.06, 4.8],
            position: [-1.35, 1.23, -0.1],
            materialId: 'camo_green',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '右侧翼子板',
            type: 'Box',
            size: [0.3, 0.06, 4.8],
            position: [1.35, 1.23, -0.1],
            materialId: 'camo_green',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '左外挂油箱',
            type: 'Cylinder',
            size: [0.18, 1.1, 0.18],
            segments: [12],
            position: [-1.25, 1.505, -1.5],
            materialId: 'camo_green',
            rotation: [1.5708, 0, 0],
            visible: true,
          },
          {
            name: '右外挂油箱',
            type: 'Cylinder',
            size: [0.18, 1.1, 0.18],
            segments: [12],
            position: [1.25, 1.505, -1.5],
            materialId: 'camo_green',
            rotation: [1.5708, 0, 0],
            visible: true,
          },
          {
            name: '左排气管',
            type: 'Cylinder',
            size: [0.06, 0.35, 0.06],
            segments: [8],
            position: [-0.8, 1.5, -2.7],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '右排气管',
            type: 'Cylinder',
            size: [0.06, 0.35, 0.06],
            segments: [8],
            position: [0.8, 1.5, -2.7],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '前大灯',
            type: 'Cylinder',
            size: [0.08, 0.1, 0.08],
            segments: [12],
            position: [-1.35, 1.34, 2.3],
            materialId: 'steel',
            rotation: [1.5708, 0, 0],
            visible: true,
          },
          {
            name: '前牵引缆绳',
            type: 'Torus',
            size: [0.25, 0.02],
            segments: [8, 16],
            position: [0, 1.15, 2.6],
            materialId: 'dark_steel',
            rotation: [1.5708, 0, 0],
            visible: true,
          },
          {
            name: '后散热格栅',
            type: 'Box',
            size: [1.8, 0.12, 0.5],
            position: [0, 1.8, -1.9],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '右后翼子板',
            type: 'BentBox',
            size: [0.6, 0.06, 0.96, 1.06],
            position: [1.2, 1.08, -2.9],
            materialId: 'camo_green',
            rotation: [-0.4712, 0, 3.1416],
            visible: true,
            segments: [32],
            color: '#4a5c2e',
          },
          {
            name: '左后翼子板',
            type: 'BentBox',
            size: [0.6, 0.06, 0.96, 1.06],
            position: [-1.2, 1.08, -2.9],
            materialId: 'camo_green',
            rotation: [-0.4887, 0, 3.1416],
            visible: true,
            segments: [32],
            color: '#4a5c2e',
          },
        ],
        rotation: [0, 0, 0],
        visible: true,
      },
      {
        name: '左履带总成',
        type: 'Group',
        position: [-1.2, 0.3, 0.5],
        children: [
          {
            name: '左负重轮1',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, 1.4],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '左负重轮2',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, 0.39],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '左负重轮3',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, -0.74],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '左负重轮4',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, -1.64],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '左负重轮5',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, -2.55],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '左主动轮',
            type: 'Cylinder',
            size: [0.3, 0.15, 0.3],
            segments: [16],
            position: [0, 0.5, -3.3],
            materialId: 'dark_steel',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '左诱导轮',
            type: 'Cylinder',
            size: [0.22, 0.15, 0.22],
            segments: [16],
            position: [0, 0.58, 2.1],
            materialId: 'dark_steel',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '左履带链',
            type: 'TrackChain',
            position: [0, 0, 0],
            materialId: 'dark_steel',
            color: '#2a2a2a',
            trackParams: {
              plateWidth: 0.55,
              plateHeight: 0.06,
              plateDepth: 0.08,
              count: 110,
              wheelRadiusFront: 0.22,
              wheelRadiusRear: 0.3,
              wheelCenterZFront: 2.1,
              wheelCenterZRear: -3.3,
              wheelCenterYFront: 0.58,
              wheelCenterYRear: 0.5,
              upperY: 0.8,
              showPath: true,
            },
            rotation: [0, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, 0, 0],
        visible: true,
      },
      {
        name: '右履带总成',
        type: 'Group',
        position: [1.2, 0.3, 0.5],
        children: [
          {
            name: '右负重轮1',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, 1.4],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '右负重轮2',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, 0.39],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '右负重轮3',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, -0.74],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '右负重轮4',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, -1.64],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '右负重轮5',
            type: 'Cylinder',
            size: [0.4, 0.12, 0.4],
            segments: [16],
            position: [0, 0.4, -2.55],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '右主动轮',
            type: 'Cylinder',
            size: [0.3, 0.15, 0.3],
            segments: [16],
            position: [0, 0.5, -3.3],
            materialId: 'dark_steel',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '右诱导轮',
            type: 'Cylinder',
            size: [0.22, 0.15, 0.22],
            segments: [16],
            position: [0, 0.58, 2.1],
            materialId: 'rubber',
            color: '#707070',
            rotation: [0, 0, 1.5708],
            visible: true,
          },
          {
            name: '右履带链',
            type: 'TrackChain',
            position: [0, 0, 0],
            materialId: 'dark_steel',
            color: '#2a2a2a',
            trackParams: {
              plateWidth: 0.55,
              plateHeight: 0.06,
              plateDepth: 0.08,
              count: 110,
              wheelRadiusFront: 0.22,
              wheelRadiusRear: 0.3,
              wheelCenterZFront: 2.1,
              wheelCenterZRear: -3.3,
              wheelCenterYFront: 0.58,
              wheelCenterYRear: 0.5,
              upperY: 0.8,
              showPath: true,
            },
            rotation: [0, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, 0, 0],
        visible: true,
      },
      {
        name: '炮塔总成',
        type: 'Group',
        position: [0, -0.15, -0.5],
        children: [
          {
            name: '炮塔座圈',
            type: 'Cylinder',
            size: [0.9, 0.08, 0.9],
            segments: [32],
            position: [0, 1.94, 0.8],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '炮塔主体',
            type: 'TaperedHex',
            size: [1.85, 0.78, 2.77, 1.45, 2.2],
            segments: [24],
            position: [0, 2.37, 0.8],
            materialId: 'camo_dark',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '指挥塔',
            type: 'Cylinder',
            size: [0.25, 0.2, 0.25],
            segments: [12],
            position: [0.4, 2.86, 0.8],
            materialId: 'camo_dark',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '装填手舱盖',
            type: 'Box',
            size: [0.4, 0.05, 0.5],
            position: [-0.2, 2.755, 0.55],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '炮管总成',
            type: 'Group',
            position: [0, 0, 0],
            children: [
              {
                name: '炮盾',
                type: 'Sphere',
                size: [0.22],
                segments: [12, 8],
                position: [0, 2.3, 2],
                scale: [1, 0.7, 0.6],
                materialId: 'barrel_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: '炮管根部',
                type: 'Cylinder',
                size: [0.11, 0.25, 0.11],
                segments: [12],
                position: [0, 2.3, 2.13],
                materialId: 'barrel_steel',
                rotation: [1.5708, 0, 0],
                visible: true,
              },
              {
                name: '主炮管',
                type: 'Cylinder',
                size: [0.06, 3.2, 0.06],
                segments: [12],
                position: [0, 2.3, 3.85],
                materialId: 'barrel_steel',
                rotation: [1.5708, 0, 0],
                visible: true,
              },
              {
                name: '炮口加强段',
                type: 'Cylinder',
                size: [0.07, 0.12, 0.07],
                segments: [12],
                position: [0, 2.3, 5.51],
                materialId: 'barrel_steel',
                rotation: [1.5708, 0, 0],
                visible: true,
              },
              {
                name: '同轴机枪',
                type: 'Cylinder',
                size: [0.03, 0.15, 0.03],
                segments: [8],
                position: [-0.12, 2.25, 2.05],
                materialId: 'dark_steel',
                rotation: [1.5708, 0, 0],
                visible: true,
              },
            ],
            rotation: [0, 0, 0],
            visible: true,
          },
          {
            name: '高射机枪',
            type: 'Group',
            position: [-0.2, 2.77, 0.9],
            rotation: [0, 0, 0],
            children: [
              {
                name: 'MG枪座底板',
                type: 'Box',
                size: [0.18, 0.02, 0.16],
                position: [0, 0, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: 'MG枪座支柱',
                type: 'Cylinder',
                size: [0.04, 0.25, 0.04],
                segments: [8],
                position: [0, 0.1, 0],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: 'MG枪身',
                type: 'Box',
                size: [0.07, 0.09, 0.18],
                position: [0, 0.27, 0.01],
                materialId: 'dark_steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: 'MG枪管',
                type: 'Cylinder',
                size: [0.012, 0.5, 0.012],
                segments: [8],
                position: [0, 0.295, 0.28],
                materialId: 'barrel_steel',
                rotation: [1.5708, 0, 0],
                visible: true,
              },
              {
                name: 'MG枪口制退器',
                type: 'Cylinder',
                size: [0.022, 0.04, 0.022],
                segments: [8],
                position: [0, 0.295, 0.55],
                materialId: 'barrel_steel',
                rotation: [1.5708, 0, 0],
                visible: true,
              },
              {
                name: 'MG弹链箱',
                type: 'Box',
                size: [0.09, 0.07, 0.13],
                position: [-0.07, 0.26, -0.01],
                materialId: 'camo_dark',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: 'MG准星座',
                type: 'Box',
                size: [0.03, 0.025, 0.05],
                position: [0, 0.305, 0.14],
                materialId: 'steel',
                rotation: [0, 0, 0],
                visible: true,
              },
              {
                name: 'MG盾牌',
                type: 'BentBox',
                size: [0.2, 0.02, 0.815, 3.141592653589793],
                position: [0, 0.09, 0],
                materialId: 'camo_dark',
                rotation: [0, -1.5708, 1.5708],
                visible: true,
                segments: [32],
                color: '#2c361b',
              },
            ],
            visible: true,
          },
          {
            name: '左扶手',
            type: 'Cylinder',
            size: [0.02, 1.2, 0.02],
            segments: [8],
            position: [-0.75, 2.68, 0.8],
            materialId: 'dark_steel',
            rotation: [1.5708, 0, 0],
            visible: true,
          },
          {
            name: '右扶手',
            type: 'Cylinder',
            size: [0.02, 1.2, 0.02],
            segments: [8],
            position: [0.75, 2.68, 0.8],
            materialId: 'dark_steel',
            rotation: [1.5708, 0, 0],
            visible: true,
          },
          {
            name: '左烟雾弹架',
            type: 'Cylinder',
            size: [0.06, 0.4, 0.06],
            segments: [8],
            position: [-0.57, 2.6, 1.34],
            materialId: 'dark_steel',
            rotation: [0.5411, 0.15, 0.2967],
            color: '#4a5c2e',
            visible: true,
          },
          {
            name: '右烟雾弹架',
            type: 'Cylinder',
            size: [0.06, 0.4, 0.06],
            segments: [8],
            position: [0.57, 2.6, 1.34],
            materialId: 'dark_steel',
            rotation: [0.5411, -0.1571, -0.2967],
            color: '#4a5c2e',
            visible: true,
          },
          {
            name: '天线基座',
            type: 'Cylinder',
            size: [0.015, 1, 0.015],
            segments: [4],
            position: [-0.4, 3.23, 0.2],
            materialId: 'dark_steel',
            rotation: [0, 0, 0],
            visible: true,
          },
        ],
        rotation: [0, 0, 0],
        visible: true,
      },
    ],
    visible: true,
  };

  // 建筑配置占位
  const BUILDING_CONFIG = {
    name: 'buildingRoot',
    type: 'Group',
    position: [0, 0, 0],
    children: [
      { name: 'wall', type: 'Box', size: [3, 2, 0.2], position: [0, 1, 0], materialId: 'concrete' },
    ],
  };

  // 敌人配置占位
  const ENEMY_CONFIG = {
    name: 'enemyRoot',
    type: 'Group',
    position: [0, 0.5, 0],
    children: [
      {
        name: 'body',
        type: 'Box',
        size: [0.5, 0.4, 0.7],
        position: [0, 0.3, 0],
        materialId: 'camo_desert',
      },
      { name: 'head', type: 'Sphere', size: [0.15], position: [0, 0.6, 0], materialId: 'steel' },
    ],
  };

  const MODEL_CONFIGS = {
    tank_v16: T34_85_V16_CONFIG,
    tiger_v16: (window.TigerIBuilder && window.TigerIBuilder.TIGER_I_V16_CONFIG) || {},
    building: BUILDING_CONFIG,
    enemy: ENEMY_CONFIG,
    hexapod: (window.HexapodConfig && window.HexapodConfig.HEXAPOD_CONFIG) || {},
    humanoid: (window.HumanoidConfig && window.HumanoidConfig.HUMANOID_BASE) || {},
  };
  let currentModelType;

  window.ModelConfigs = {
    T34_85_V16_CONFIG,
    BUILDING_CONFIG,
    ENEMY_CONFIG,
    get TIGER_I_V16_CONFIG() {
      return (window.TigerIBuilder && window.TigerIBuilder.TIGER_I_V16_CONFIG) || {};
    },
    get HEXAPOD_CONFIG() {
      return (window.HexapodConfig && window.HexapodConfig.HEXAPOD_CONFIG) || {};
    },
    get HUMANOID_BASE() {
      return (window.HumanoidConfig && window.HumanoidConfig.HUMANOID_BASE) || {};
    },
    MODEL_CONFIGS,
  };
  window.ModelConfigs.currentModelType = 'hexapod';
})();
